---
title: "Interactive Report Demo"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(ggplot2)
library(dplyr)
theme_set(theme_bw())
library(DT)
library(plotly)
```

```{r create_a_dataset}
df = data.frame(ID = 1:50,
                Group = c(rep('A', 25), rep('B', 23), rep('b', 2)),
                Gender = rep(c('F', 'M'), 25),
                Weight = round(rnorm(50, 140, 25), 2),
                Outcome = round(c(rnorm(25, 15, 2), 
                                    rnorm(23, 25, 3), 
                                    rnorm(2, 25, 3)), 2))
```


Data Profile
=======================================================================

Column {data-width=500}
-----------------------------------------------------------------------

### Participant Cohort

```{r }
df %>%
  ggplot(aes(x = Group, fill = Group)) +
  geom_bar() +
  ylab('Sample Size') +
  theme(legend.position = 'top') 

```
```{r fix_label}
df$Group <- toupper(df$Group)
```

Column {data-width=500}
-----------------------------------------------------------------------

### Print first 10 rows

```{r}
DT::datatable(df, filter = 'top', options = list(pageLength = 10, autoWidth = T))
```


Group Comparision 
=======================================================================

Column {data-width=800}
-----------------------------------------------------------------------

### Compare Groups

```{r}
fig <- 
  ggplot(df,
       aes(x = Group, y = Outcome, col = Group)) +
  geom_jitter(aes(shape = Gender), 
              height = 0, width = .2) +
  geom_boxplot(fill = NA, outlier.colour = NA, show.legend = F) 

ggplotly(fig)  %>%
    layout(title = "",
           legend = list(orientation = "h",   
                         # show entries horizontally
                         xanchor = "center",  
                         # use center of legend as anchor,
                         x = .5,
                         y = 40))


```

Geographics Visualization
=======================================================================

Column {data-width=800}
-----------------------------------------------------------------------

### Geographics Data 

```{r}
data(canada.cities, package = "maps")
viz <- ggplot(canada.cities, aes(long, lat)) +
  borders(regions = "canada") +
  coord_equal() +
  geom_point(aes(text = name, size = pop), colour = "red", alpha = 1/2)
ggplotly(viz, tooltip = c("text", "size"))

```

Scatterplot Visualization
=======================================================================

Column {data-width=800}
-----------------------------------------------------------------------

### Linked scatterplot brushing 

```{r}
# linked scatterplot brushing
d <- highlight_key(mtcars)

qplot(data = d, x = mpg, y = wt) %>%
  subplot(qplot(data = d, x = mpg, y = vs)) %>% 
  layout(title = "Click and drag to select points") %>%
  highlight("plotly_selected")
```

